baseURL = "https://defrance-maud.github.io/"
languageCode = "fr-fr"
title = "Maud DEFRANCE - Dieteticienne nutritionniste"
publishDir = "docs"
[permalinks]
  recettes = "/recettes/:year/:month/:title/"