baseURL = "https://defrance-maud.github.io/"
languageCode = "fr-fr"
title = "Maud DEFRANCE - Dieteticienne nutritionniste"
disableKinds = ["taxonomy", "taxonomyTerm"]
[permalinks]
  recettes = "/recettes/:year/:month/:title/"